//Constants that we'll use as Actions for different events

export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';
export const INTERNET_CHANGED = 'INTERNET_CHANGED';



export const IS_USER_AUTHENTICATED = 'IS_USER_AUTHENTICATED';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

export const PICK_PROFILE_PICTURE = 'PICK_PROFILE_PICTURE'
export const RESET_APP_STATE = 'RESET_APP_STATE';

export const STORE_SESSION_FCM_TOKEN = 'STORE_SESSION_FCM_TOKEN';
